#!/bin/bash
#
# This file is part of SleepProxyClient.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Andreas Weinlein <andreas.dev@weinlein.info>
# @copyright Copyright (c) 2012-2023 Andreas Weinlein
#
# SleepProxyClient is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# SleepProxyClient is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with SleepProxyClient. If not, see <http://www.gnu.org/licenses/>.

. /etc/default/sleepproxyclient

TAG="sleepproxyclient"
SCRIPTDIR="/usr/share/sleepproxyclient/scripts"

case $1 in
pre|suspend|hibernate)
## RUN BEFORE SUSPEND OR HIBERNATE
	# Restart avahi to ensure it is alive and usable
	service avahi-daemon restart
	# avahi might need some additional time to fully start up
	sleep 2

	logger -t $TAG "running sleepproxyclient"
	bash $SCRIPTDIR/sleepproxyclient.sh

	if [ "${SPC_RTC_WAKE}" != "" ] ; then
		logger -t $TAG "Setting RTC Alarm"
		echo `date '+%s' -d "+ ${SPC_LEASE_TIME} seconds"` > "/sys/class/rtc/${SPC_RTC_WAKE}/wakealarm"
	fi
	logger -t $TAG "done: $?"
;;
post|thaw|resume)
## RUN AFTER RESUME AND
## AFTER RESUME FROM SUSPEND TO DISK

	if [ "$SPC_DEBUG" != "" ] ; then
		logger -t $TAG "awake!"
	fi

	# Restart avahi to ensure it is alive and usable
	service avahi-daemon restart

	if [ "${SPC_RTC_WAKE}" != "" ] ; then
		# Ensure RTC alarm is cleared on wake
		echo 0 > "/sys/class/rtc/${SPC_RTC_WAKE}/wakealarm"
	fi
;;
esac
