#!/bin/bash
#
# This file is part of SleepProxyClient.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Andreas Weinlein <andreas.dev@weinlein.info>
# @copyright Copyright (c) 2012 Andreas Weinlein
#
# SleepProxyClient is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# SleepProxyClient is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with SleepProxyClient. If not, see <http://www.gnu.org/licenses/>.


## INSTALL:
## move or link to:
##		/etc/pm/sleep.d/00sleepproxyclient
## script has to be executable (chmod +x)

## This script calls sleepproxyclient.sh
## for all configured interfaces on suspend or hibernate


TAG="sleepproxyclient"
SCRIPTDIR="/usr/share/sleepproxyclient/scripts"

case $1 in
suspend|hibernate)
## RUN BEFORE SUSPEND OR HIBERNATE
	service avahi-daemon restart
	
	logger -t $TAG "running SPC"
	bash $SCRIPTDIR/sleepproxyclient.sh
	logger -t $TAG "done: $?"

;;
thaw|resume)
## RUN AFTER RESUME AND
## AFTER RESUME FROM SUSPEND TO DISK

	if [ "$SPC_DEBUG" != "" ] ; then
		logger -t $TAG "awake!"
	fi
	
	service avahi-daemon restart

;;
esac


