#!/bin/sh
#
# This file is part of SleepProxyClient.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Andreas Weinlein <andreas.dev@weinlein.info>
# @copyright Copyright (c) 2012 Andreas Weinlein
#
# SleepProxyClient is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# SleepProxyClient is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with SleepProxyClient. If not, see <http://www.gnu.org/licenses/>.

set -e

case "$1" in
	configure)
		# remove the old file if present
		test -e /etc/pm/sleep.d/00sleepproxyclient && rm /etc/pm/sleep.d/00sleepproxyclient
		test -e /etc/pm/sleep.d/00_sleepproxyclient && rm /etc/pm/sleep.d/00_sleepproxyclient

		# fix executables
		chmod +x /usr/share/sleepproxyclient/scripts/*
		
		test -e /etc/pm/sleep.d/00_sleepproxyclient && ln -s /usr/share/sleepproxyclient/scripts/00_sleepproxyclient /etc/pm/sleep.d/00_sleepproxyclient
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
		echo "postinst called with unknown argument '$1'" >&2
		exit 1
	;;
esac

exit 0
