name: Build release artifacts
on:
  workflow_dispatch:
    types: []
  push:
    tags:        
      - v*.*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Build Debian package
        uses: dawidd6/action-debian-package@v1
        with:
          artifacts_directory: deb
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: Debian packages
          path: deb/*.deb
          retention-days: 7
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: deb/*.deb
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
